import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    flowerdocsLanding: [
        { type: "doc", id: "index", label: "Overview" }
    ],
    concepts: [{ type: "autogenerated", dirName: "concepts" }],
    install: [{ type: "autogenerated", dirName: "install" }],
    learn: [{ type: "autogenerated", dirName: "learn" }],
    config: [{ type: "autogenerated", dirName: "config" }],
    apis: [{ type: "autogenerated", dirName: "apis" }],
    connecteurs: [{ type: "autogenerated", dirName: "connecteurs" }],
};

export default sidebars;
