
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    uxopianGettingStarted: [{ type: "autogenerated", dirName: "getting_started" }],
    uxopianUnderstanding: [{ type: "autogenerated", dirName: "understanding" }],
    uxopianHowTo: [{ type: "autogenerated", dirName: "how_to" }],
    uxopianExtending: [{ type: "autogenerated", dirName: "extending" }],
    uxopianReference: [{ type: "autogenerated", dirName: "reference" }],
    uxopianAdmin: [{ type: "autogenerated", dirName: "admin" }],
    uxopianReleaseNotes: [{ type: "autogenerated", dirName: "release_notes" }],
};

export default sidebars;
