import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    fast2: [
        {
            type: "autogenerated",
            dirName: ".",
        },
    ],
};

export default sidebars;
