import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Fast2',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'fast2' }],
    },
    {
      type: 'category',
      label: 'ARender',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'arender' }],
    },
    {
      type: 'category',
      label: 'FlowerDocs',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'flowerdocs' }],
    },
    {
      type: 'category',
      label: 'Uxopian AI',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'uxopian-ai' }],
    },
  ],
};

export default sidebars;