
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    uxopianGettingStarted: [{ type: "autogenerated", dirName: "getting_started" }],
    uxopianConcepts: [{ type: "autogenerated", dirName: "concepts" }],
    uxopianArchitecture: [{ type: "autogenerated", dirName: "architecture" }],
    uxopianConfig: [{ type: "autogenerated", dirName: "configuration" }],
    uxopianAdmin: [{ type: "autogenerated", dirName: "administration" }],
    uxopianGuides: [{ type: "autogenerated", dirName: "how_to_guides" }],
};

export default sidebars;
