
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    fast2GettingStarted: [{ type: "autogenerated", dirName: "getting-started" }],
    fast2Components: [{ type: "autogenerated", dirName: "components" }],
    fast2Catalog: [{ type: "autogenerated", dirName: "catalog" }],
    fast2Advanced: [{ type: "autogenerated", dirName: "advanced" }],
    fast2Cookbooks: [{ type: "autogenerated", dirName: "cookbooks" }],
    fast2Api: [{ type: "autogenerated", dirName: "API" }],
    fast2Documents: [{ type: "autogenerated", dirName: "documents" }],
};

export default sidebars;
