
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    arenderWhatIs: [{ type: "autogenerated", dirName: "what-is-arender" }],
    arenderInstall: [{ type: "autogenerated", dirName: "installation" }],
    arenderLearn: [{ type: "autogenerated", dirName: "learn" }],
    arenderGuides: [{ type: "autogenerated", dirName: "guides" }],
    arenderFeatures: [{ type: "autogenerated", dirName: "features" }],
    arenderDev: [{ type: "autogenerated", dirName: "development" }],
};

export default sidebars;
