
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    arender: [
        {
            type: "doc",
            id: "index",
            label: "Overview",
        },
        {
            type: "category",
            label: "Quickstart",
            items: [{ type: "autogenerated", dirName: "quickstart" }],
        },
        {
            type: "category",
            label: "Installation",
            items: [{ type: "autogenerated", dirName: "install" }],
        },
        {
            type: "category",
            label: "Operation",
            items: [{ type: "autogenerated", dirName: "operation" }],
        },
        {
            type: "category",
            label: "Features",
            items: [{ type: "autogenerated", dirName: "feature" }],
        },
        {
            type: "category",
            label: "APIs",
            items: [{ type: "autogenerated", dirName: "apis" }],
        },
        {
            type: "category",
            label: "Configuration",
            items: [{ type: "autogenerated", dirName: "configuration" }],
        },
        {
            type: "category",
            label: "Performance",
            items: [{ type: "autogenerated", dirName: "performance" }],
        },
        {
            type: "category",
            label: "Connectors",
            items: [{ type: "autogenerated", dirName: "connector" }],
        },
        {
            type: "category",
            label: "Cookbooks",
            items: [{ type: "autogenerated", dirName: "cookbook" }],
        },
        {
            type: "category",
            label: "FAQ",
            items: [{ type: "autogenerated", dirName: "faq" }],
        },
    ],
};

export default sidebars;
