arender.server.rendition.hosts=http://service-broker:8761/
arender.server.alfresco.atom.pub.url=http://alfresco:8080/alfresco/api/-default-/cmis/versions/1.1/atom
arender.server.alfresco.user=admin
arender.server.alfresco.password=admin
